version: "3"
services:
  nginx:
    ports:
      - "3000:80"

  my-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=docker123
      - SESSION_SECRET=secret324524
      - REDIS_MAXAGE=30000
    command: npm run dev
    