version: "3"
services:
  nginx:
    ports:
      - "80:80"

  my-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASSWORD=docker123
      - SESSION_SECRET=secret25235
    command: npm start