version: "3"
services:
  my-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=docker123
    command: npm run dev
    