version: "3"
services:
  my-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=docker123
    volumes:
      - db:/data/db

volumes:
  db: