version: "3"
services:
  my-app:
    build:
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASSWORD=docker123
    command: npm start