version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  my-app:
    build: .
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    image: mongo
    volumes:
      - db:/data/db

  redis:
    image: redis

volumes:
  db: